name: crop_image_example
description: Example for crop_image.
version: 1.0.1
homepage: https://github.com/deakjahn/crop_image
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  crop_image: ^1.0.15
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  crop_image:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/08272011229.jpg